# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 564d8bc24a18a8d2d6f9fdd9954fea0498f7c7a3667302439b342b561c1cef799e40f5b42e1076966807e0272efa5bd6947365f35448ef05dea075e7e6a5eb03

test:
  secret_key_base: bd369acd814f16ce70879e7bd2ce8add946115a8650dbe6ef65f0f213c00311d2acb48191cadd1a8d0068ea45432355b86447adaf5a0c5e28b2f530b3a8f95c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
